// apps/portfolio/src/components/Projects.tsx
import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';

interface Project {
  id: string;
  title: string;
  description: string;
  techStack: string[];
  githubUrl: string;
}

export default function Projects() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [selectedTech, setSelectedTech] = useState<string[]>([]);

  const allTech = useMemo(() => {
    const set = new Set<string>();
    projects.forEach((p) => p.techStack.forEach((t) => set.add(t)));
    return Array.from(set).sort();
  }, [projects]);

  const fetchProjects = async () => {
    try {
      const params = new URLSearchParams();
      if (query.trim()) params.set('q', query.trim());
      if (selectedTech.length > 0) params.set('tech', selectedTech.join(','));
      const url = `http://localhost:3000/api/projects${params.toString() ? `?${params.toString()}` : ''}`;
      const response = await axios.get(url);
      setProjects(response.data);
    } catch (error) {
      console.error('Error fetching projects:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchProjects();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    // Refetch when filters change
    fetchProjects();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query, selectedTech.join(',')]);

  const toggleTech = (tech: string) => {
    setSelectedTech((prev) =>
      prev.includes(tech) ? prev.filter((t) => t !== tech) : [...prev, tech]
    );
  };

  return (
    <section>
      <h2 className="text-3xl font-bold text-secondary mb-4">Projects</h2>

      <div className="mb-6 flex flex-col gap-3">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search by title or description..."
          className="w-full md:w-1/2 border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
        />

        {allTech.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {allTech.map((tech) => {
              const active = selectedTech.includes(tech);
              return (
                <button
                  key={tech}
                  onClick={() => toggleTech(tech)}
                  className={
                    `px-3 py-1 rounded-full text-sm border ` +
                    (active
                      ? 'bg-primary text-white border-primary'
                      : 'bg-white text-primary border-primary/40 hover:border-primary')
                  }
                >
                  {tech}
                </button>
              );
            })}
          </div>
        )}
      </div>

      {loading ? (
        <div>Loading projects...</div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {projects.map((project) => (
            <div
              key={project.id}
              className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow"
            >
              <div className="p-6">
                <h3 className="text-xl font-semibold text-secondary mb-2">{project.title}</h3>
                <p className="text-gray-600 mb-4">{project.description}</p>
                <div className="flex flex-wrap gap-2 mb-4">
                  {project.techStack.map((tech) => (
                    <span
                      key={tech}
                      className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm"
                    >
                      {tech}
                    </span>
                  ))}
                </div>
                <a
                  href={project.githubUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center text-primary hover:text-primary/80 transition-colors"
                >
                  View on GitHub
                  <svg className="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                </a>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

// apps/dashboard/src/views/Projects.vue
<template>
  <div class="projects">
    <h1>Projects</h1>

    <div class="filters">
      <input
        v-model="query"
        type="text"
        placeholder="Search by title or description..."
        class="input"
      />
      <div v-if="allTech.length" class="tech-filter">
        <button
          v-for="tech in allTech"
          :key="tech"
          @click="toggleTech(tech)"
          :class="['tag', selectedTech.includes(tech) ? 'active' : '']"
        >
          {{ tech }}
        </button>
      </div>
    </div>

    <div class="projects-grid">
      <div v-for="project in projects" :key="project.id" class="project-card">
        <h3>{{ project.title }}</h3>
        <p class="description">{{ project.description }}</p>
        <div class="tech-stack">
          <span v-for="tech in project.techStack" :key="tech" class="tech-tag">
            {{ tech }}
          </span>
        </div>
        <a :href="project.githubUrl" target="_blank" class="github-link"> View on GitHub </a>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, computed } from 'vue';
import axios from 'axios';

interface Project {
  id: string;
  title: string;
  description: string;
  techStack: string[];
  githubUrl: string;
  userId: string;
}

const projects = ref<Project[]>([]);
const query = ref('');
const selectedTech = ref<string[]>([]);

const allTech = computed(() => {
  const set = new Set<string>();
  projects.value.forEach((p) => p.techStack.forEach((t) => set.add(t)));
  return Array.from(set).sort();
});

const fetchProjects = async () => {
  try {
    const params = new URLSearchParams();
    if (query.value.trim()) params.set('q', query.value.trim());
    if (selectedTech.value.length > 0) params.set('tech', selectedTech.value.join(','));
    const url = `/api/projects${params.toString() ? `?${params.toString()}` : ''}`;
    const response = await axios.get(url);
    projects.value = response.data;
  } catch (error) {
    console.error('Error fetching projects:', error);
  }
};

const toggleTech = (tech: string) => {
  selectedTech.value = selectedTech.value.includes(tech)
    ? selectedTech.value.filter((t) => t !== tech)
    : [...selectedTech.value, tech];
};

onMounted(fetchProjects);
watch([query, selectedTech], fetchProjects, { deep: true });
</script>

<style scoped>
.projects {
  max-width: 1200px;
  margin: 0 auto;
}

.filters {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.input {
  border: 1px solid #d1d5db;
  border-radius: 6px;
  padding: 0.5rem 0.75rem;
}

.tech-filter {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.tag {
  border: 1px solid #93c5fd;
  color: #2563eb;
  background: white;
  border-radius: 9999px;
  padding: 0.25rem 0.75rem;
  font-size: 0.9rem;
}

.tag.active {
  background: #2563eb;
  color: white;
  border-color: #2563eb;
}

.projects-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
  gap: 1.5rem;
  margin-top: 2rem;
}

.project-card {
  background: white;
  padding: 1.5rem;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.project-card h3 {
  margin: 0;
  color: #2c3e50;
  font-size: 1.2rem;
}

.description {
  margin: 1rem 0;
  color: #34495e;
  line-height: 1.5;
}

.tech-stack {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin: 1rem 0;
}

.tech-tag {
  background: #e1f0fa;
  color: #3498db;
  padding: 0.25rem 0.75rem;
  border-radius: 15px;
  font-size: 0.9rem;
}

.github-link {
  display: inline-block;
  margin-top: 1rem;
  color: #3498db;
  text-decoration: none;
  font-weight: 500;
}

.github-link:hover {
  text-decoration: underline;
}
</style>
